# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact', '0002_auto_20160810_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='Reverse ID of a CMS page to redirect to', max_length=255, verbose_name='URL Redirection'),
        ),
    ]
